
name: Generate Speed × FF Reports

on:
  workflow_dispatch:
    inputs:
      tx_csv:
        description: 'Path to transaction time CSV in repo'
        required: false
        default: 'data/Patient Transaction Time Report.csv'
      fee_glob:
        description: 'Glob for fee/donation Excel files'
        required: false
        default: 'data/Fee_*Transactions*.xlsx'
      exclusions:
        description: 'Path to exclusions JSON'
        required: false
        default: 'config/exclusions.json'
      peak_hours:
        description: 'Comma-separated peak hours (24h)'
        required: false
        default: '15,16,17,18,19'
  push:
    paths:
      - 'data/**'
      - 'config/exclusions.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate reports
        env:
          TX: ${{ github.event.inputs.tx_csv }}
          FEE: ${{ github.event.inputs.fee_glob }}
          EXC: ${{ github.event.inputs.exclusions }}
          PEAK: ${{ github.event.inputs.peak_hours }}
        run: |
          python scripts/generate.py             --tx "${TX:-data/Patient Transaction Time Report.csv}"             --fee-glob "${FEE:-data/Fee_*Transactions*.xlsx}"             --exclusions "${EXC:-config/exclusions.json}"             --peak-hours "${PEAK:-15,16,17,18,19}"             --out out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: speed-ff-reports
          path: out/**

